### PR TITLE
Drain nodes by default on upgrade

### PR DESCRIPTION
**Pull request by anmazzotti**
This PR enables drain options by default on `ManagedOSImages`
With defaults:

```yaml
  drain:
    force: true
    skipWaitForDeleteTimeout: 60
```

### CODE REVIEW

**Comment by anmazzotti** [comment]
Having some issues with it: 

```
test-c00616c7-e1e9-422c-a786-9bcd826cd8fd:~ # kubectl -n cattle-system logs apply-os-upgrader-dev-upgrade-on-test-c00616c7-e1e9-422c-cjdxcs -c drain
node/test-c00616c7-e1e9-422c-a786-9bcd826cd8fd cordoned
error: unable to drain node "test-c00616c7-e1e9-422c-a786-9bcd826cd8fd" due to error:cannot delete daemonsets.apps "svclb-traefik-d10b2f0b" is forbidden: User "system:serviceaccount:cattle-system:os-upgrader-dev-upgrade" cannot get resource "daemonsets" in API group "apps" in the namespace "kube-system": kube-system/svclb-traefik-d10b2f0b-5vwz4, continuing command...
There are pending nodes to be drained:
 test-c00616c7-e1e9-422c-a786-9bcd826cd8fd
cannot delete daemonsets.apps "svclb-traefik-d10b2f0b" is forbidden: User "system:serviceaccount:cattle-system:os-upgrader-dev-upgrade" cannot get resource "daemonsets" in API group "apps" in the namespace "kube-system": kube-system/svclb-traefik-d10b2f0b-5vwz4

```

There is a flag to ignore DaemonSets, but I think we need to fix the permissions too.

**Comment by anmazzotti** [comment]
Tested by draining a node with a deployment, statefulset, and replicaset applied to it. 
Seems like those permissions are not needed and the existing GET pods is just fine, with the addition of  `pods/eviction` and `daemonsets` permission:

```
test-c00616c7-e1e9-422c-a786-9bcd826cd8fd:~ # kubectl -n cattle-system logs apply-os-upgrader-dev-upgrade-on-test-c00616c7-e1e9-422c-cfxzpg -c drain
node/test-c00616c7-e1e9-422c-a786-9bcd826cd8fd cordoned
WARNING: ignoring DaemonSet-managed Pods: kube-system/svclb-traefik-d10b2f0b-5vwz4
evicting pod kube-system/traefik-768bdcdcdd-fdbtd
evicting pod cattle-fleet-system/fleet-agent-7f9ccfb8b-jrfnk
evicting pod cattle-system/cattle-cluster-agent-dbf99485f-txbrj
evicting pod cattle-system/rancher-webhook-7dc6679459-r6gzv
evicting pod default/frontend-gpg6w
evicting pod default/nginx-deployment-cbdccf466-thfvd
evicting pod default/web-0
evicting pod kube-system/coredns-77ccd57875-gff4h
evicting pod kube-system/local-path-provisioner-957fdf8bc-dtcjd
evicting pod kube-system/metrics-server-648b5df564-4pvpk
pod/frontend-gpg6w evicted
pod/traefik-768bdcdcdd-fdbtd evicted
pod/metrics-server-648b5df564-4pvpk evicted
pod/cattle-cluster-agent-dbf99485f-txbrj evicted
pod/web-0 evicted
pod/fleet-agent-7f9ccfb8b-jrfnk evicted
pod/nginx-deployment-cbdccf466-thfvd evicted
pod/local-path-provisioner-957fdf8bc-dtcjd evicted
pod/coredns-77ccd57875-gff4h evicted
pod/rancher-webhook-7dc6679459-r6gzv evicted
node/test-c00616c7-e1e9-422c-a786-9bcd826cd8fd drained
```

**Review by davidcassany — APPROVED** [review]
LGTM

**Review by fgiudici — APPROVED** [review]
looks good!

**Comment by anmazzotti** [comment]
@davidcassany  @fgiudici 

Putting the PR back to draft since it breaks tests.
The root cause is that configuring `drain: null` still leads to the default being populated and the drain option is now untoggable. 

This needs to be fixed, not only for the tests. 

Any idea? I tried to remove the `+optional` from the kubebuilder comments, but didn't help. 
I feel like the only option would be to add a `drain.enabled` field.

**Comment by fgiudici** [comment]
> @davidcassany @fgiudici
> 
> Putting the PR back to draft since it breaks tests. The root cause is that configuring `drain: null` still leads to the default being populated and the drain option is now untoggable.
> 
> This needs to be fixed, not only for the tests.
> 
> Any idea? I tried to remove the `+optional` from the kubebuilder comments, but didn't help. I feel like the only option would be to add a `drain.enabled` field, or an outer `drainEnabled` field if we don't want to wrap the system-upgrade-controller DrainSpec, but that's a technical detail.
> 
> Edit: Trying `+nullable` now

 I'm wondering... does it make any sense to allow to *not* drain a node on upgrade? 🤔

**Comment by anmazzotti** [comment]
> > @davidcassany @fgiudici
> > Putting the PR back to draft since it breaks tests. The root cause is that configuring `drain: null` still leads to the default being populated and the drain option is now untoggable.
> > This needs to be fixed, not only for the tests.
> > Any idea? I tried to remove the `+optional` from the kubebuilder comments, but didn't help. I feel like the only option would be to add a `drain.enabled` field, or an outer `drainEnabled` field if we don't want to wrap the system-upgrade-controller DrainSpec, but that's a technical detail.
> > Edit: Trying `+nullable` now
> 
> I'm wondering... does it make any sense to allow to _not_ drain a node on upgrade? 🤔

It does for our tests. 
There may also be instances where you don't care about draining, for some reason. 
It is fixed now and the field is nullable.

**Pull request merged**
