### PR TITLE
Remove SLE Micro reference from elemental-operator images

### PR DESCRIPTION
**Pull request by davidcassany**

### CODE REVIEW

**Comment by davidcassany** [comment]
@fgiudici this is how I would tag the images from the chart. I would not include references to the SLE Micro version as those images are including really few things and they are really not related to any OS version. The same should apply for the channel images, ideally we should be capable to list images from multiple SLE Micro versions within the same image, hence adding a SLE Micro reference within the channel URI looks like a confusing idea to me. Only the OS images (and probably its helper images to build isos) should be clearly related to the underlaying SLE Micro version IMHO.

@kkaempf how do you feel about it?

**Comment by davidcassany** [comment]
I'd like this to merge this after https://github.com/rancher/elemental-docs/pull/187 as this also implies another URL change, but only for the `next` version.

**Comment by davidcassany** [comment]
Blocked waiting for https://github.com/rancher/elemental-docs/pull/187

**Review by fgiudici — APPROVED** [review]
Love the changes ❤️

**Pull request merged**
