### PR TITLE
Only decode some smbios data

### PR DESCRIPTION
**Pull request by Itxaka**
We dont need to have all the available data from the smbios, we can just
send the needed parts.

The handles are all fixed via the SMBIOS reference specification[0]

[0] https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.6.0.pdf

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by kkaempf — APPROVED** [review]
Ok as a workaround. This probably needs some testing about the time overhead of spawing `dmicode` six times instead of one.

**Review by fgiudici — APPROVED** [review]
smart way to limit smbios data!

**Comment by Itxaka** [comment]
> Ok as a workaround. This probably needs some testing about the time overhead of spawing dmicode six times instead of one.


Doesnt dmidecode just reads and parses /sys/firmware/dmi/tables/DMI ? The usual cache mechanisms (disk, memory) should hit here and the runtime be negligent no? can you run `time dmidecode` on a big server several times to see how much time it takes the first time VS the 6th?

**Comment by Itxaka** [comment]
on my local tests (but this is a normal tower) it actually takes more to run the full command that to run with the type flag.

```
zeus:~ # time dmidecode
.....
real	0m0.014s
user	0m0.002s
sys	0m0.000s
```

```
zeus:~ # time dmidecode -t 12
.....
real	0m0.001s
user	0m0.000s
sys	0m0.001s
```

once the cache is hot, further calls to the full dmidecode now bring the time down, but the first one is the slow one.

**Comment by Itxaka** [comment]
with a simple benchmark

```
func BenchmarkDecode(b *testing.B) {
	for i := 0; i < b.N; i++ {
		Decode()
	}
}
```


results (old is main, new is this branch)
```
name      old time/op  new time/op  delta
Decode-8  1.67ms ± 0%  1.68ms ± 0%  +0.26%  (p=0.015 n=9+8)
```

Again, this is on a normal tower, we would need a beefy server with a lot of cards and shit to test it properly

**Pull request merged**
