### PR TITLE
Build operator with GCO in Dockerfile

### PR DESCRIPTION
**Pull request by Itxaka**
Otherwise it cant enable tpm emulation on register

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by kkaempf** [comment]
Hmm, in OBS a full [go-tpm-tools](https://github.com/google/go-tpm-tools/archive/refs/tags/go-tpm-tools-0.3.8.tar.gz) tarball is required for a successful build 🤔

**Comment by Itxaka** [comment]
on the dockerfile because we call go mod download it will download the full tpm-tools and compile, thus thats why it needs gcc and such

**Comment by Itxaka** [comment]
still testing btw, but it should work like the binary which also is compiled from scratch to use tpm emulation

**Comment by Itxaka** [comment]
mmmh I dont think this is supposed to work....

Its compiled with musl but executed on a non-musl env, so it should fail, it does locally...

**Review by fgiudici — DISMISSED** [review]
LGTM!

**Comment by Itxaka** [comment]
nah, if we want tpm emulation to work AND be able to copy the file AND be able to run elemental-operator from the docker instance, this wont work.

 So:
 - CGO_ENABLED=0:
 	- Works on docker container
 	- Works to be copied into the final image on elemental
 	- Does not support tpm emulation
 - CGO_ENABLED=1:
 	- Works on docker container
 	- Does not work once copied to elemental (built with musl)
 	- Supports tpm-emulation

So Im leaving it as is, we will rework this when needed

**Pull request closed without merging**
