### PR TITLE
Use YAML content for Elemental Agent config

### LINKED ISSUE #764: /etc/rancher/elemental/agent/config.yaml is a JSON file
```
test-btrfs-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c:/ # cat /etc/rancher/elemental/agent/config.yaml 
{"workDirectory":"/var/lib/elemental/agent/work","localPlanDirectory":"/var/lib/elemental/agent/plans","appliedPlanDirectory":"/var/lib/elemental/agent/applied","remoteEnabled":true,"connectionInfoFile":"/var/lib/elemental/agent/elemental_connection.json"}
```

This currently works miraculously due to the yaml parser in use by the system agent: https://github.com/rancher/system-agent/blob/main/pkg/config/config.go#L11C3-L11C19

If this changes, then we won't be able to parse the config file anymore. 

A simple change is to just use the .json extension to name the file.

Another possibility is to extend the [forked api](https://github.com/rancher/elemental-operator/blob/main/internal/system-agent/api.go#L71) and add `yaml` keys so that we can marshal correctly, but I would not do that until it's also done by the system-agent.

### PR DESCRIPTION
**Pull request by anmazzotti**
Fixes #764 
Should also be backported to 1.6.x

### CODE REVIEW

**Comment by fgiudici** [comment]
Good catch!
Well, seems we are lucky enough that the kuberntes-sigs yaml parser can also fix our use case: it allows to use json struct tags to serialize with yaml (see https://github.com/kubernetes-sigs/yaml ).
So, if that is true, it should be as easy as using `yaml.Marshal` instead of `json.Marshal` in the getAgentConfigBytes() here:
https://github.com/rancher/elemental-operator/blob/2c3f177fd253eb0c401890fabed319667aced9cf/pkg/install/install.go#L409C1-L409C52

**Comment by anmazzotti** [comment]
I'd like not to depend on that yaml parser if possible, as I find it a bit confusing to not have explicit yaml definitions. That's how currently works however, since that parser is used by the system-agent.

Just using .json is also supported, so I opted for that route since we already marshal it.

**Comment by fgiudici** [comment]
It is perfectly fine  to rename the config file to .json (since the contents are already in json format indeed).
Anyway, what doesn't look that great is to introduce branches in the code to manage  old and new versions. I know we already do in some parts, but would be better if we could avoid it whenever possible.

**Comment by anmazzotti** [comment]
> It is perfectly fine to rename the config file to .json (since the contents are already in json format indeed). Anyway, what doesn't look that great is to introduce branches in the code to manage old and new versions. I know we already do in some parts, but would be better if we could avoid it whenever possible.

That only applies to the elemental-support, and it wasn't even working previously anyway, so I could simply eliminate the branch there and collect .json only.

**Comment by anmazzotti** [comment]
@fgiudici I refactored it to actually use YAML after you pointed out conflict with the [elemental-system-agent.service](https://github.com/rancher/elemental/blob/main/framework/files/usr/lib/systemd/system/elemental-system-agent.service#L17) file.

**Review by fgiudici — APPROVED** [review]
Looks good!

**Pull request merged**
