### PR TITLE
OBS: add ssl default certificates in SeedImage build image

### PR DESCRIPTION
**Pull request by fgiudici**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

```

### CODE REVIEW

**Comment by kkaempf** [comment]
I don't fully get this change. Looks like you're overriding the just installed certificates with the one's from the host container.
What am I missing ?

**Review by davidcassany — CHANGES_REQUESTED** [review]
mmmm I dislike this approach. There must be a better way to feed this files than copying it from the build env.

I'd first try by
```
RUN /usr/sbin/update-ca-certificates
```

In the FROM scratch image.

**Review by frelon — APPROVED** [review]

**Comment by davidcassany** [comment]
I gave a quick run to `RUN /usr/sbin/update-ca-certificates` and seams to work. I did a build [here](https://build.opensuse.org/package/show/home:dcassany:Elemental:Dev:Teal53/seedimage-builder)  and certificates are loaded in `/var/lib/ca-certificates/openssl/`

**Comment by fgiudici** [comment]
> mmmm I dislike this approach. There must be a better way to feed this files than copying it from the build env.
> 
> I'd first try by
> 
> ```
> RUN /usr/sbin/update-ca-certificates
> ```
> 
> In the FROM scratch image. I would have expected the `ca-certificates-mozilla` package do so in some `post` scriptlet, probably it does not.

It does in the base image, but it fails (guess doesn't like the --installroot).
Yep, running in the scratch image is the way to go 👍🏼 

@kkaempf , with the update-ca-certificates failing the openssl ca-cert directory stays empty. So, this explains the _brutal_ cp in the original commit.
Going with David suggestion...

**Review by davidcassany — APPROVED** [review]
LGTM

**Comment by fgiudici** [comment]
> I gave a quick run to `RUN /usr/sbin/update-ca-certificates` and seams to work. I did a build [here](https://build.opensuse.org/package/show/home:dcassany:Elemental:Dev:Teal53/seedimage-builder) and certificates are loaded in `/var/lib/ca-certificates/openssl/`

yep, I just tested the image built on OBS (my branch) targeting the branch in this PR, it is fixed

**Review by kkaempf — APPROVED** [review]
:+1:

**Pull request merged**
