### PR TITLE
tests(registration): More unit tests

### PR DESCRIPTION
**Pull request by Itxaka**
And more dumb fake objects

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
lgtm

**Review by davidcassany — APPROVED** [review]
Looks good! Finally we are getting some proper structure for tests :+1:

I am wondering if it would make sense adding something like CodeCov reports in this repo, basically to easily identify PRs that have a big impact on tests coverage and do not neglect unit tests in the future.

**Comment by Itxaka** [comment]
> I am wondering if it would make sense adding something like CodeCov reports in this repo, basically to easily identify PRs that have a big impact on tests coverage and do not neglect unit tests in the future.

Been fighting with codecov for 2 days. reports wont appear for some reason for forks. I think its wrongly installed or something so it doesnt have access. Reports are uploaded properly but codecov fails to get branches and crap so it doesn't post back into PRs.

Its a mess, even thinking of just going to another provider because its terrible. Even wrote them and they told me to bugger off basically ¬_¬

**Comment by Itxaka** [comment]
welp, now it works of course. @davidcassany do you have actions enabled in your fork of the elemental-operator repo?

**Comment by Itxaka** [comment]
ok I think I fixed it somehow after experimenting with the apps I guess?

**Comment by davidcassany** [comment]
> ok I think I fixed it somehow after experimenting with the apps I guess?

Cool it works now ;) I have not tested neither checked if in my fork it works... I tend to use my forks only for testing builds including artifacts in multiple repositories (so I don need to merge in other repos just for testing)

Anyway, something to probably keep in mind for the coverage analysis is setting it to all packages within  the repository. In elemental client we have this at ginkgo call

```
--coverpkg=github.com/rancher/elemental-cli/...
```
I remember I added it to track coverage beyond the package being tested, this way if running tests of package A some lines from package B are executed they are also included in coverage analysis. Anyway this can be added/tested in a separate PR.

**Comment by Itxaka** [comment]
> I tend to use my forks only for testing builds including artifacts in multiple repositories (so I don need to merge in other repos just for testing)

I ask because as soon as I removed disabled actions in my fork, it started working. So Im not sure if it had something to do...when checking the empty report it showed that CI had failed, which was not true. Im wondering if its running CI twice (fork and main) and getting the wrong results somehow...

**Pull request merged**
