### PR TITLE
Use cacert from rancher and use serverl-url from rancher

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

Fixes https://github.com/rancher/elemental-operator/issues/32

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
Cool!

**Review by mjura — APPROVED** [review]
LGTM

**Review by frelon — APPROVED** [review]
Even better :+1:

**Review by mjura — APPROVED** [review]
Good job 👌

**Pull request merged**
