### PR TITLE
Adds ca-certificates and ca-certificates-mozilla in operator image

### PR DESCRIPTION
**Pull request by davidcassany**
related to #483

### CODE REVIEW

**Comment by kkaempf** [comment]
#484 ?! 😮 😆

**Review by kkaempf — APPROVED** [review]

**Review by anmazzotti — APPROVED** [review]
Looks good, but I wonder if it would be better to have the install `--no-recommends`  dependencies on a new line, just in case one day we may add recommended packages in elemental-operator. 

Or maybe if this is already a case where we should recommend `ca-certificates` and `ca-certificates-mozilla` in our spec file.

**Comment by davidcassany** [comment]
> Looks good, but I wonder if it would be better to have the install `--no-recommends` dependencies on a new line, just in case one day we may add recommended packages in elemental-operator.

Generally speaking I dislike the concept of a weak dependencies for containers, usually the approach should be starting from the bare minimum (just strict runtime dependencies) and keep adding stuff little by little as we see fit. I am also not sure if the `--no-recommends` is already the default for the base image, it used to be the case long in past, but I am not sure it is currenlty the case nowadays. No strong opinion, but I prefer being explicit for weak dependencies, like including them in the Dockerfile so anyone having a look at it sees it.

> Or maybe if this is already a case where we should recommend `ca-certificates` and `ca-certificates-mozilla` in our spec file.

No strong opinion here, we could include them. But I'd still use the `--no-recommends` in the Dockerfile as who knows what `ca-certificates` requires and recommends and what are the recommendations and requirements of required and recommended packages. Including recommended packages can easily span the dependecy tree to something huge.

**Comment by davidcassany** [comment]
For the records this change doubles the size of the image. We increase from ~45MB to ~80MB when uncompressed.

**Comment by kkaempf** [comment]
> For the records this change doubles the size of the image. We increase from ~45MB to ~80MB when uncompressed disappointed

Hmm 🤔 
~~~
> rpm -qi ca-certificates
Size        : 28727
> rpm -qi ca-certificates-mozilla
Size        : 1000746
~~~

**Pull request merged**
