### PR TITLE
Merge kubebuilder branch into main

### PR DESCRIPTION
**Pull request by alexander-demicev**

### CODE REVIEW

**Comment by davidcassany** [comment]
Lets consider https://github.com/rancher/elemental-operator/pull/277#issuecomment-1335267978

We probably should cut a release of the current main before merging this

**Comment by alexander-demicev** [comment]
@davidcassany sure, this PR is just a draft.

**Comment by fgiudici** [comment]
I would lean to try to speed up moving kubebuilder on the main branch: all development should be done on the kubebuilder branch from now on (IMO), so I would switch soon as possible. Sure, we have to tag before switching.
I would also consider branching a stable-1.0.x branch for the "old" code (Will kubebuilder  be the 1.1.x version?).
Maybe we could plan the switch, do it as soon as e2e tests are ok-ish, and we all take a couple of days following the switch to review / test and fix the kubebuilder (now "main") branch. Something to discuss next week :-)

**Comment by davidcassany** [comment]
> Maybe we could plan the switch, do it as soon as e2e tests are ok-ish, and we all take a couple of days following the switch to review / test and fix the kubebuilder (now "main") branch. Something to discuss next week :-)

Sure, my intention would be to cut a (pre)-release (tag and validate staging, nothing else) next Monday then I'd say we are almost ready to merge this branch. Currently running e2e tests for kubebuilder 🤞🏽

**Comment by davidcassany** [comment]
Since we have a [green run of the e2e tests](https://github.com/rancher/elemental/actions/runs/3642668127) and the manual tests are functional I believe it is time to merge this branch.

**Review by Itxaka — APPROVED** [review]

**Comment by Itxaka** [comment]
lets gooooo

**Comment by davidcassany** [comment]
Merging last Dev built of this branch just passed [e2e tests](https://github.com/rancher/elemental/actions/runs/3674678543)! 🥳

**Pull request merged**
