### PR TITLE
Add Metadata CRD

### LINKED ISSUE #711: Wrong default cloud config file with standard user
See https://github.com/rancher/elemental-ui/issues/175

### PR DESCRIPTION
**Pull request by anmazzotti**
Closes #711 

As suggested by @aalves08 I created a new `UISettings` CRD that we can use to propagate the `appVersion` and `annotations` from charts. 

```yaml
kubectl -n cattle-elemental-system get uisettings -o yaml
apiVersion: v1
items:
  - apiVersion: elemental.cattle.io/v1beta1
    kind: UISettings
    metadata:
      annotations:
        meta.helm.sh/release-name: elemental-operator
        meta.helm.sh/release-namespace: cattle-elemental-system
      creationTimestamp: "2024-04-23T12:39:11Z"
      generation: 1
      labels:
        app.kubernetes.io/managed-by: Helm
      name: elemental-operator
      namespace: cattle-elemental-system
      resourceVersion: "7104"
      uid: 4f3d97e6-dd73-4ad1-aca2-3436d81f97ab
    spec:
      annotations:
        catalog.cattle.io/auto-install: elemental-operator-crds=match
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/display-name: Elemental
        catalog.cattle.io/kube-version: '>= 1.23.0-0'
        catalog.cattle.io/namespace: cattle-elemental-system
        catalog.cattle.io/os: linux
        catalog.cattle.io/permits-os: linux
        catalog.cattle.io/provides-gvr: elemental.cattle.io/v1beta1
        catalog.cattle.io/rancher-version: '>= 2.7.0-0'
        catalog.cattle.io/release-name: elemental-operator
        catalog.cattle.io/scope: management
        catalog.cattle.io/type: cluster-tool
        catalog.cattle.io/upstream-version: v1.6.0-dev
      appVersion: v1.6.0-dev
```

### CODE REVIEW

**Comment by aalves08** [comment]
Also, with this work moving forward, we might ditch what @fgiudici did here: https://github.com/rancher/elemental-operator/issues/691 (sorry about that 😢 )

So that you guys don't need to maintain this on two different places.

FYI @davidcassany

**Comment by anmazzotti** [comment]
> Also, with this work moving forward, we might ditch what @fgiudici did here: #691 (sorry about that 😢 )
> 
> So that you guys don't need to maintain this on two different places.
> 
> FYI @davidcassany

No problem at all. Labels are gone now, thank you for pointing out.

**Comment by fgiudici** [comment]
Thanks Andrea, the PR is pretty good  👍🏼 
While looking at the code I realized this is something we will likely never change or drop. There are two things I would consider to change:
1) the kind name:  "UISettings" refers to what we want the resource to be used for but not what it actually contains. I would consider something more generic and not related to UI, like "Version", "Versioning", "Metadata",  ... you name it. 
2) having "annotations" in the spec: why not having a dummy object then, with no spec at all, and just use the metadata annotations?

Something like:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: versions.elemental.cattle.io
spec:
  group: elemental.cattle.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
  scope: Namespaced
  names:
    plural: versions
    singular: version
    kind: Version

```

Otherwise, I would then really go with a "UISettings" or "UIFeatures" CRD, but then in the spec I would put a "features" map[string]bool to enable (or disable) specific features of the UI extension.

**Comment by anmazzotti** [comment]
> 1. Metadata

I raised this point with the team and we decided for `Metadata` as it's generic enough.

**Review by fgiudici — APPROVED** [review]
LGTM

**Pull request merged**
