### PR TITLE
coverity: make patch status informational

### PR DESCRIPTION
**Pull request by fgiudici**
...so, it should not block the merging.

### CODE REVIEW

**Comment by fgiudici** [comment]
> # [Codecov](https://codecov.io/gh/rancher/elemental-operator/pull/219?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher) Report
> 
> Base: **40.70**% // Head: **40.63**% // Decreases project coverage by **`-0.07%`** warning

what ?!? 🤷🏼 🤣

**Comment by Itxaka** [comment]
> > # [Codecov](https://codecov.io/gh/rancher/elemental-operator/pull/219?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher) Report
> > Base: **40.70**% // Head: **40.63**% // Decreases project coverage by **`-0.07%`** warning
> 
> what ?!? 🤷🏼 rofl
unicorn-magic

**Review by mjura — APPROVED** [review]
LGTM

**Comment by fgiudici** [comment]
Branch rebased on master: will not wait for all tests as this doesn't change the operator code, it just changes coverity config.

**Pull request merged**
