### PR TITLE
Add slem4r images in channel

### PR DESCRIPTION
**Pull request by davidcassany**
Part of rancher/elemental#1008

### CODE REVIEW

**Comment by davidcassany** [comment]
This PR switches from elemental-teal-channel to elemental-channel. The new elemental-channel includes all previous Teal images and brings the new SLE Micro 4 Rancher image. 

I think this is the cleanest way to migrate. On upgrades this will cause the following:

* helm deletes elemental-teal-channel and all the associated versions
* helm creates the new elemental-channel including all versions, previous and new ones

**Comment by davidcassany** [comment]
On ISO creation the drop down menu with this PR looks like
image

**Review by fgiudici — APPROVED** [review]
sure 👍🏼

**Comment by davidcassany** [comment]
Finally got green tests for [UI](https://github.com/rancher/elemental/actions/runs/6643083461) and [CLI](https://github.com/rancher/elemental/actions/runs/6639717240) 🎉

**Pull request merged**
