### PR TITLE
Revert "Split header into 7Kb of data"

### PR DESCRIPTION
**Pull request by kkaempf**
Reverts rancher/elemental-operator#133
#134 is an alternative approach.

### CODE REVIEW

**Review by fgiudici — APPROVED** [review]

**Comment by Itxaka** [comment]
should be blocked, currently it fixes the issue but its not the more elegant approach.

**Comment by kkaempf** [comment]
Why is the _revert_ blocked ?

**Comment by kkaempf** [comment]
Didn't we favor #134 over #133. #133 got merged yesterday and should be reverted, no ?!

**Comment by kkaempf** [comment]
After discussion, we'll keep #133 for the time being.

**Pull request closed without merging**
