### PR TITLE
Log the version, commit and commit date on start

### LINKED ISSUE #37: Log version, github commit id, or build time
When `elemental-operator` starts up under Rancher Manager, this is what I see in its log

```
time="2022-07-13T11:44:57Z" level=info msg="Starting controller at namespace cattle-elemental-system. Upgrade sync interval at: 1h0m0s"                                                    │
time="2022-07-13T11:44:57Z" level=info msg="Applying CRD managedosimages.elemental.cattle.io"                                            
...
```

what I'd like to see is something like

```
time="2022-07-13T11:44:56Z" level=info msg="elemental-operator, version 0.1.1 @bcfe4d0, built 2022-Jul-13 11:32Z"
...

### PR DESCRIPTION
**Pull request by Itxaka**
Both for installer and operator, the first thing they now do is log the
version, commit and commit date on start

Fixes #37 

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
```
time="2022-07-14T09:21:11Z" level=info msg="Operator version v0.1.1, commit 09f06ea0e0eb31b74e5b3a84b58f65f11a3ba3b2, commit date 2022-07-14T09:37:45Z"
```

**Comment by Itxaka** [comment]
This works the same across locally built binaries, docker images and released binaries via goreleaser

**Review by kkaempf — CHANGES_REQUESTED** [review]
I would need a way to pass git commit / date from the outside into the Makefile.
When building in OBS, I don't have a git checkout, just a source tarball.

**Comment by Itxaka** [comment]
@kkaempf there is already a way of doing that by passing the COMMITDATE and GIT_TAG to the makefile:

```
# itxaka @ zeus in ~/projects/elemental-operator on git:version_expand o [9:53:18] 
$ COMMITDATE=yesterday GIT_TAG=458.12.1 make build 
go build -ldflags '-w -s -X "github.com/rancher/elemental-operator/pkg/version.Version=458.12.1" -X "github.com/rancher/elemental-operator/pkg/version.Commit=bf5519527e06e607f148c6d2e9773dfc5f344a9d" -X "github.com/rancher/elemental-operator/pkg/version.CommitDate=yesterday"' -o build/elemental-operator /home/itxaka/projects/elemental-operator/cmd/operator
go build -ldflags '-w -s -X "github.com/rancher/elemental-operator/pkg/version.Version=458.12.1" -X "github.com/rancher/elemental-operator/pkg/version.Commit=bf5519527e06e607f148c6d2e9773dfc5f344a9d" -X "github.com/rancher/elemental-operator/pkg/version.CommitDate=yesterday"' -o build/elemental-installer /home/itxaka/projects/elemental-operator/cmd/installer
```

Now, interestingly enough, maybe the commitdate in that case is not needed or difficult to get, so you can pass an empty string.

**Comment by Itxaka** [comment]
how are tests failing when I only added one var goddammit

**Review by kkaempf — APPROVED** [review]
Looks good, thanks !

**Review by fgiudici — APPROVED** [review]
LGTM!

**Pull request merged**
