### PR TITLE
Add CAs to docker artifact

### LINKED ISSUE #118: elemental-operator images need ca data in them
When testing the channel version resources, using the json one, it tries to fetch data from the internet but it fails due to not being able to check the certificate. This is because the operator image only contains the binary on it thus any normal GET to an external resource will fail.

This should be a very simple fix:

`COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/`

### PR DESCRIPTION
**Pull request by Itxaka**
Fixes #118 
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
Tested to work

**Comment by Itxaka** [comment]
@kkaempf this requires no changes in OBS because in there we bundle the whole image witht he operator, while in here we just have the operator binary

**Comment by fgiudici** [comment]
Do we need this to allow the packaged elemental-register to recognize public signed SSL certs for the registration channel?
It took me a while to realize this could be the reason... can we add a comment to explain why we need it in the Docker file? Or even just a line in the commit message would be enough 😄

**Comment by Itxaka** [comment]
> Do we need this to allow the packaged elemental-register to recognize public signed SSL certs for the registration channel?
It took me a while to realize this could be the reason... can we add a comment to explain why we need it in the Docker file? Or even just a line in the commit message would be enough smile

Yes, but this should only affect GitHub builds as those are stripped of everything and only the binary is available.

OBS build are the whole sles image(should we change to sle-micro-rancher?) so those have the certs already in there.

**Comment by fgiudici** [comment]
Uh, just saw the "Fixes https://github.com/rancher/elemental-operator/issues/118"... Sorry! Looks good!

**Review by fgiudici — APPROVED** [review]

**Comment by kkaempf** [comment]
> @kkaempf this requires no changes in OBS because in there we bundle the whole image witht he operator, while in here we just have the operator binary

Actually, I'd like to have exactly this in OBS too. But there `FROM scratch` isn't allowed :-(

**Pull request merged**
